### ISSUE TITLE
FAIL test/react-solid-state.spec.js

### ISSUE THREAD

**Issue by SanichKotikov** [ryansolid/solid#249]
I've run `npm test` and got this issue:

```
react-solid-state: > react-solid-state@0.21.1 test /open-source/solid/packages/react-solid-state
react-solid-state: > jest
react-solid-state: FAIL test/react-solid-state.spec.js
react-solid-state:   ● Test suite failed to run
react-solid-state:     Cannot find module 'solid-js' from 'src/index.js'
react-solid-state:     Require stack:
react-solid-state:       src/index.js
react-solid-state:       test/react-solid-state.spec.js
react-solid-state:     > 1 | import {
react-solid-state:         | ^
react-solid-state:       2 |   createState,
react-solid-state:       3 |   createEffect,
react-solid-state:       4 |   createMemo,
react-solid-state:       at Resolver.resolveModule (../../node_modules/jest-resolve/build/index.js:307:11)
react-solid-state:       at Object.<anonymous> (src/index.js:1:1)
react-solid-state: Test Suites: 1 failed, 1 total
react-solid-state: Tests:       0 total
react-solid-state: Snapshots:   0 total
react-solid-state: Time:        1.891 s
react-solid-state: Ran all test suites.
```

node v14.0.0
npm v6.14.8
osx v10.15.7

I'm doing something wrong, Maybe there is something I should do before npm test? Or it's known issue?

**Comment by ryansolid** [comment]
`npm i` and `npm run build`. Lerna needs to create the symlinks and needs to build the dist folder for other projects to use.
