### ISSUE TITLE
npm init solid app <app-name> throw an error `Cannot read property 'endsWith' of undefined`

### ISSUE THREAD

**Issue by Relaxe111** [ryansolid/solid#56]
Hello, when i try to start a project with command `npm init solid app my-name` i've got an error like : `
C:\Sites\solidjs>npm init solid app solid-app-1

Creating a new Solid app in C:\Sites\solidjs\solid-app-1.

C:\Users\User\AppData\Roaming\npm\node_modules\create-solid\createSolid.js:217
  const useYarn = process.env._.endsWith('yarn') && shouldUseYarn()
                                ^

TypeError: Cannot read property 'endsWith' of undefined
    at createApp (C:\Users\User\AppData\Roaming\npm\node_modules\create-solid\createSolid.js:217:33)
    at Object.<anonymous> (C:\Users\User\AppData\Roaming\npm\node_modules\create-solid\createSolid.js:182:1)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\Users\User\AppData\Roaming\npm\node_modules\create-solid\index.js:58:1)

`
i have same issue when i use `yarn create solid app <my-name>`
could anyone help me?/

**Comment by ryansolid** [comment]
Hmm.. I wonder if this is a Windows issue with difference in process.env. Admittedly this code was added for smart detection of yarn versus npm. I believe I have now fixed the error to fallback to npm in this case. But I wasn't able to reproduce this locally. Let me know if this works for you now.

**Comment by Relaxe111** [comment]
It workek perfectly! thokyou. I realy belive that this project has future !
